---
title: "Manuscript Te example"
author: "Lauren Buckley"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Function testing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Load TrenchR package
library(TrenchR)
library(maptools)
library(ggplot2)
```



#Microclimate calculations
```{r}
setwd("/Volumes/GoogleDrive/Shared drives/TrEnCh/Projects/TrenchR/data/")
dat=read.csv("microclimate_C1.csv", sep=",", na.strings = c("-49.99","NA"))
```
```{r}
#ANALYZE SURFACE ROUGHNESS AND PROFILES
C1all$day=  as.POSIXlt(as.character(C1all$datetime),tz='MST', format="%m/%d/%Y %H:%M")$mday
C1all$hour=as.POSIXlt(as.character(C1all$datetime),tz='MST', format="%m/%d/%Y %H:%M")$hour 

C1.dayhr<- aggregate(C1all[,c(2:8,13:22)], by=list(C1all$day, C1all$hour), FUN=mean, na.rm=TRUE)
names(C1.dayhr)[1:2]=c("day","hour")
C1.hr<- aggregate(C1all[,c(2:8,13:22)], by=list(C1all$hour), FUN=mean, na.rm=TRUE)
names(C1.hr)[1]="hour"

C1.hr= as.matrix(C1.hr)
```

We can estimate surface roughness across hours:
```{r}
#surface roughness
z0= apply(C1.hr[, c("Wind0.25m","Wind0.5m","Wind1m","Wind1.5m")], FUN=surface_roughness, MARGIN=1, zr=c(0.25,0.5,1.0,1.5))

```

We calculate the temperature and windspeed profiles for a given hour using multiple functions in TrenchR.
```{r}
z.seq <- seq(0, 2, by = 0.1)

#subset to day and hour
C1.sub= subset(C1.dayhr, C1.dayhr$day==10)
hr=10

#estimate profiles
#temperature
t.seq1= sapply(z.seq, FUN=air_temp_profile_neutral, T_r=C1.sub[hr,"Air0.5m"], z0=z0[hr], zr=0.5, T_s=C1.sub[hr,"Soil"])

t.seq2= sapply(z.seq, FUN=air_temp_profile, T_r=C1.sub[hr,"Air0.5m"], u_r=C1.hr[hr,"Wind0.5m"], zr=0.5, z0=z0[hr], T_s=C1.sub[hr,"Soil"])

t.seq3= sapply(z.seq, FUN=air_temp_profile_segment, T_r=C1.sub[hr, c("Air0.25m","Air0.5m","Air1.0m","Air1.5m")],u_r=C1.sub[hr, c("Wind0.25m","Wind0.5m","Wind1m","Wind1.5m")], zr=c(0.25,0.5,1,1.5), z0=rep(z0[hr],4), T_s=C1.sub[hr,"Soil"])

#windspeed
u.seq1= sapply(z.seq, FUN=wind_speed_profile_neutral, u_r=C1.sub[hr,"Wind0.5m"], zr=0.5, z0=z0[hr])

u.seq2= sapply(z.seq, FUN=wind_speed_profile, u_r=C1.sub[hr,"Wind0.5m"], zr=0.5, z0=z0[hr])

u.seq3= sapply(z.seq, FUN=wind_speed_profile_segment, u_r=C1.sub[hr, c("Wind0.25m","Wind0.5m","Wind1m","Wind1.5m")], zr=c(0.25,0.5,1,1.5), z0=rep(z0[hr],4))

#replace infinity with N
t.seq1[which(!is.finite(t.seq1))]=NA
```

We then plot the temperature and windspeed profiles.
```{r}
plot(t.seq1, z.seq, type = "l", xlab = "Temperature (C)", ylab = "z (height above ground in m)")
points(t.seq2, z.seq, type = "l", lty="dashed")
points(t.seq3, z.seq, type = "l", lty="dotted")
points(C1.sub[hr, c("Air0.25m","Air0.5m","Air1.0m","Air1.5m")], c(0.25,0.5,1,1.5), type = "l", col="red")

plot(u.seq1, z.seq, type = "l", xlab = "windspeed (m/s)", ylab = "z (height above ground in m)")
points(u.seq2, z.seq, type = "l", lty="dashed")
points(u.seq3, z.seq, type = "l", lty="dotted")
points(C1.sub[hr, c("Wind0.25m","Wind0.5m","Wind1m","Wind1.5m")], c(0.25,0.5,1,1.5), type = "l", col="red")
```

#Te calculation
```{r}

#Grasshopper data
setwd("/Volumes/GoogleDrive/Shared drives/TrEnCh/Projects/TrenchR/data/")
spec.dat=read.csv("SpecData.csv")

#read weather data
dat=read.csv("DatAll_Pace2011.csv", sep=",", na.strings = c("-49.99","NA"))
#match site data
sites=read.csv("SiteElevations.csv", sep=",")

#combine soil temperatures
dat$SoilTemp= rowMeans(dat[,c("SoilTemp","SoilTemperature")], na.rm = TRUE) 

#ditch problematic temperatures
dat$Temp[dat$Temp< -10]=NA

#add elevation
match1= match(dat$site, sites$Site)
dat$Elev=sites[match1,"Elevation"]

#----------------

z<-0.001 #specify distance from ground 

#calculate Julian day
date.ct <- strptime(dat$datetime, format="%m/%d/%Y %H:%M", tz="MST")
dat$J= round(as.numeric(julian(date.ct, origin = as.Date("2011-01-01") )))
dat$hour= date.ct$hour

#match site data
match1= match(dat$site, sites$Site) 
dat$lon= sites$Lon[match1]
dat$lat= sites$Lat[match1]

#Calculate zenith
dat$psi= zenith_angle(dat$J,lat=dat$lat, lon=dat$lon, hour=dat$hour)

#Subset to August
dat.dt<- strptime(dat$datetime, format="%m/%d/%Y %H:%M", tz="MST") #as.Date
dataug= subset(dat, dat.dt$mon==7)
#subset to day
dat= subset(dataug, dataug$Rad>5)

#scale temperature to ground
dat$Tgrass <- air_temp_profile(T_r=dat$Temp, u_r=dat$Wind, zr=0.5, z0=0.02, z=z, T_s=dat$SoilTemp)

#cut nas
dat= dat[,c("Rad","Temp","Wind","SoilTemp","SanguinipesTemp","Elev","J", "hour","psi","Tgrass")]
dat= na.omit(dat)
```


```{r}
##Calculate Te for each species
dat$Te<-Tb_grasshopper(T_a=dat$Tgrass, T_g=dat$SoilTemp, u=dat$Wind, H=dat$Rad, K_t=0.7, psi=dat$psi, L=0.0211, Acondfact=0.01)  #T_a=dat$Tgrass
#fix infinite
dat$Te[is.infinite(dat$Te)]<-NA
#ditch big numbers for now
dat$Te[dat$Te>100]<-NA
```

```{r}
#estimate convective heat transfer coefficient

#Estimate using empirical relationship
dat$H_L=heat_transfer_coefficient(V=dat$Wind,D=0.0211,K=0.025, nu= 15.3 * 10^(-6) , taxa="cylinder")

#Also illustrate estimations using a spherical approximation and a simplified version of the approximation.
H_L1= heat_transfer_coefficient_approximation(V=dat$Wind,D=0.0211,K= 0.025, nu= 15.3 * 10^(-6), taxa="flyinginsect")
H_L2= heat_transfer_coefficient_simple(V=dat$Wind,D=0.0211)

#surface area
A= sa_from_length(l=0.0211)
```

```{r}
#Gates calculation
TeGates= rep(NA, nrow(dat) )

 for(ind in 1:nrow(dat) ){
   out= try(Tb_Gates(A=A, D=0.0211/3, psa_dir=0.66, psa_ref=1-0.66, psa_air=1, psa_g=0.01, T_g=dat$SoilTemp[ind]+273, T_a=dat$Tgrass[ind]+273, Qabs=A*dat$Rad[ind], epsilon=0.95, H_L=dat$H_L[ind], ef=1.3, K=0.15), silent=TRUE)
 if(is.numeric(out))TeGates[ind]=out
 }
  dat$TeGates=TeGates-273.15
```

```{r}
#aggregate by day and hour
dat.dh= suppressWarnings(aggregate(dat, by=list(dat$Elev, dat$hour, dat$J), FUN=mean, na.rm=TRUE))
```

```{r}
#aggregate by hour
dat.h= suppressWarnings(aggregate(dat, by=list(dat$Elev, dat$hour), FUN=mean, na.rm=TRUE))
```

```{r}
library(reshape2)
#convert to long format
dat.s= melt(dat.h, id = c("Elev", "J","hour","psi"))

#plot
dat.s= subset(dat.s, dat.s$variable %in% c("Temp","SoilTemp","SanguinipesTemp","Te","Tgrass","TeGates") )

ggplot(data=dat.s, aes(x=hour, y = value, color=variable))+geom_line(aes(lty=variable) )+facet_wrap(~Elev)

```
```{r}
#plot by date time
dat.dh$Jhr= dat.dh$J +dat.dh$hour/24

#convert to long format
dat.s= melt(dat.dh, id = c("Elev", "J","hour","psi","Jhr"))

#plot
dat.s= subset(dat.s, dat.s$variable %in% c("Temp","SoilTemp","SanguinipesTemp","Te","Tgrass","TeGates") )

plot.t=ggplot(data=dat.s, aes(x=Jhr, y = value, color=variable))+geom_line(aes(lty=variable) )+facet_grid(Elev~1)
```

```{r}
setwd("/Volumes/GoogleDrive/Shared drives/TrEnCh/Projects/TrenchR/figures/")

pdf("TeTime.pdf", height = 10, width = 15)
plot.t
dev.off()

```
